[book]
authors = ["青山"]
language = "zh"
multilingual = false
src = "src"
title = "笔记"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/qingshan/notes"
git-repository-icon = "fa-github"
